name: Pull Request Test
on:
  pull_request:
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up python and install uv
        uses: ./.github/actions/setup
        with:
          python-version: 3.11
          uv-version: 0.6.14
      - name: Run tests
        uses: ./.github/actions/test
